nodes:
    get_all_orders:
        endpoint_id: orders/get_orders
    get_all_users:
        endpoint_id: users/get_users
    map_users_orders:
        endpoint_id: users/map_users_orders
        dependencies:
            orders/get_orders:
              - get_all_orders_result
            users/get_users:
              - get_users_result
failure_strategy: ignore
