app:
  shutdown-timeout: 10s

http:
  port: 8080

metrics:
  http:
    port: 2112

logs:
  path: logs/shortcut.log

mongo:
  uri: "mongodb://localhost:27017"
  database: "shortcut"

cache:
  addr: "localhost:6379"
