{{- if .Values.shortcut.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shortcut.fullname" . }}-config
  labels:
    {{- include "shortcut.labels" . | nindent 4 }}
data:
  base.yaml: |
{{ toYaml .Values.shortcut.config.base | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shortcut.fullname" . }}-graphs
  labels:
    {{- include "shortcut.labels" . | nindent 4 }}
data: {{- if not .Values.shortcut.graphConfigs }} {}{{- end }}
{{- range $name, $content := .Values.shortcut.graphConfigs }}
  {{ $name }}: |
{{ $content | indent 4 }}
{{- end }}
{{- end }}
