{{- if and .Values.shortcut.enabled .Values.shortcut.serviceMonitor.enabled (index .Values "kube-prometheus-stack" "enabled") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "shortcut.fullname" . }}
  labels:
    {{- include "shortcut.labels" . | nindent 4 }}
    {{- with .Values.shortcut.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "shortcut.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.shortcut.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.shortcut.serviceMonitor.scrapeTimeout }}
{{- end }}
