nodes:
  validate-user:
    endpoint-id: user-service/get-user
    dependencies:
      - node-id: input
        item-id: http_request
        overriden-item-id: request
  validate-product:
    endpoint-id: product-service/validate-product
    dependencies:
      - node-id: input
        item-id: http_request
        overriden-item-id: request
  add-cart-item:
    endpoint-id: user-service/add-cart-item
    dependencies:
      - node-id: validate-user
        item-id: user
      - node-id: validate-product
        item-id: product

output-node: add-cart-item
failure-strategy: revert
