nodes:
  get-user:
    endpoint-id: user-service/get-user
    dependencies:
      - node-id: input
        item-id: http_request
        overriden-item-id: request
  get-product:
    endpoint-id: product-service/get-product
    cache:
      enabled: true
      ttl-ms: 10000000
    dependencies:
      - node-id: input
        item-id: http_request
        overriden-item-id: request
      - node-id: get-user
        item-id: user
  get-recommendations:
    endpoint-id: recommendation-service/get-recommendations
    dependencies:
      - node-id: input
        item-id: http_request
        overriden-item-id: request
      - node-id: get-user
        item-id: user
  list-recommended-products:
    endpoint-id: product-service/list-products
    dependencies:
      - node-id: get-recommendations
        item-id: recommendations
  render:
    endpoint-id: frontend-service/render-product-page
    dependencies:
      - node-id: get-product
        item-id: product
      - node-id: list-recommended-products
        item-id: products
        overriden-item-id: recommendations

output-node: render
failure-strategy: ignore
